name: "GModStore Deployment"
description: "Deploy scripts to GModStore"
author: "John Internet <internet@doctor-internet.dev>"
branding:
  icon: check
  color: blue

runs:
  using: node16
  main: "dist/index.js"

inputs:
  token:
    description: "GModStore API Token"
    required: true
  product:
    description: "The ID of the addon to deploy to."
    required: true
  version:
    description: "The new version name to deploy."
    required: true
  type:
    description: "The type of version to deploy. Can be stable, beta, alpha, private or demo. If omitted, uses '-type' at the end of version string (if it exists), otherwise uses stable"
    required: false
    default: "stable"
  changelog:
    description: "Markdown formatted changelog."
    required: true
    default: "No changelog."
  path:
    description: "Path to the addon. This must be in zip format."
    required: true
  baseurl:
    description: "API Base URL"
    required: true
    default: "https://gmodstore.com/api/v3/"
