name: Test

on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm i
          npm run build
      - name: Test
        uses: ./
        with:
          product: ${{ secrets.GMS_ADDON_ID }}
          token: ${{ secrets.GMS_TOKEN }}
          version: 1.0.0
          type: private
          path: tests/test.zip
